### ISSUE TITLE
Problem with a Nginx 502 Bad Gateway answer on `http://localhost:8000/api/v1/projects` GET request

### ISSUE THREAD

**Issue by CharlyP** [taigaio/taiga-vagrant#18]
Hi I just updated my local copy of the repository, destroyed my previous VM and run a vagrant up and I have this silent issue when trying to register a new account or even when I load the homepage of Taiga on localhost:8000

**Comment by jespino** [comment]
Thanks for your feedback, we have to test it again with the last release.

**Comment by superalex** [comment]
Hello @CharlyP ,

taiga-scripts needed a small update for installing two extra packages, it should be working now. If you make a "vagrant destroy" and a "vagrant up" again you should have the latest taiga version working ;)

Regards!,

**Comment by CharlyP** [comment]
Waouw thanks for the speed of the fix ;)

**Comment by superalex** [comment]
You are welcome!, and sorry for the inconvenience!  ;)
