### ISSUE TITLE
How to Get Email Sending

### ISSUE THREAD

**Issue by grooveion** [taigaio/taiga-vagrant#19]
First, let me say thank you to the Taiga team. What an amazing project management tool. Lightning fast, beautiful & intuitive interface and immediately accessible to an agile newbie! 

Second, let me thank you for this  vagrant script. The last time I tried to get a demo of a django app going on a test server it took me hours. I was able to run this vagrant script and in less than 15 minutes had a working Taiga install!

On to the "Issue". This is really just a public service announcement for the next newbie that installs this via vagrant. After starting to enter projects into the system, I immediately wanted to share, so I started inviting others to login and check it out. I invited them to the project and received an "ok"  that an invitation was sent and the users existed as "pending" in my project. They didn't receive the email. I couldn't see any obvious way to pre-approve them and change them from the pending status and dug a little deeper into the Taiga install documentation. 

I ended up modifying he ~/taiga-back/settings/local.py on the vagrant server to connect with gmail's smtp server:

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'yourusername@gmail.com'
EMAIL_HOST_PASSWORD = 'yourpassword'

Now it is possible that any well respected Django Developer already knows this but in the interest of making your app accessible to even the newbies, might I suggest that you add this (or something to this effect) to the README?

**Comment by superalex** [comment]
Hello @grooveion, 

Thank you very much for your comments, the vagrant installation should work if there is an email server running in localhost and listening in the 25 port so I think it would be easier to add the installation of an email server (postfix, sendmail...) to the provision.sh script. What do you think about it?

Regards!,

**Comment by RafaAguilar** [comment]
As an additonal note, 

I used an external custom Postfix with SSL and just change the `EMAIL_USE_TLS = True` for `EMAIL_USE_SSL = True`, following this [guide](https://docs.djangoproject.com/en/1.7/topics/email/)

I know this isn't completely related to original ticket, but on any other email related tickets couldn't find this. May be this could help someone.

**Comment by superalex** [comment]
Thank you very much @RafaAguilar :+1:
