### ISSUE TITLE
taiga-vagrant fails to provide a working taiga environment

### ISSUE THREAD

**Issue by NikosAlexandris** [taigaio/taiga-vagrant#21]
**Thank you** for this excellent platform!

Using `taiga-vagrant` I got only a running virtual machine. I needed to manually get and run the `setup-server.sh` taiga-script. Isn't `taiga-vagrant` supposed to render needless any further effort to get a working platform? At least this is my understanding reading the relevant [documentation](http://taigaio.github.io/taiga-doc/dist/setup-alternatives.html#setup-taiga-vagrant)

**Comment by superalex** [comment]
Hello @NikosAlexandris is it possible that you had a network problem while installing?, taiga-vagrant should finish with a working Taiga instance...

**Comment by NikosAlexandris** [comment]
Alejandro:

> Hello @NikosAlexandris is it possible that you had a network problem
> while installing?, taiga-vagrant should finish with a working Taiga
> instance...

I thought so too.  But I tried in another place, with a fast and solid
connection and I have had the same issue.  I will likely retry the
process again.

Nikos

**Comment by NikosAlexandris** [comment]
@superalex Are there any "unsual" ports involved in taiga-vagrant, in getting it ready to work?  Perhaps these ports, if they are instructed, were blocked in/through the (university owned) network I tried to perform the setup (as some friend suggested).

**Comment by superalex** [comment]
Not involved during the installation, it just tries to download a lot of packages for the taiga-back requirements and clone some repos.

If you install taiga-vagrant out of the university network, is it working?, I did a fresh taiga-vagrant install in my machine some minutes ago and it was working perfectly.

**Comment by NikosAlexandris** [comment]
What details would be useful to know (next time I'll try this)?

**Comment by superalex** [comment]
I think there is nothing special to check but can you browse the logs shown while installing to check if something is wrong.

**Comment by NikosAlexandris** [comment]
Does this help any further:
```
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period. This can
mean a number of things.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

I guess I need to "fix" something.

**Comment by superalex** [comment]
It sounds like you are having problems with your Virtualbox configuration (I assume it's the virtualization system you are using). If you launch manually Virtualbox and try to boot the virtual machine probably will receive some more information about what can be happening.

You should also check that you can access internet from your virtual machine so it can install everything needed.

Regards!,

**Comment by NikosAlexandris** [comment]
As far as I know, the only unusual thing I've set up myself in my working Funtoo box (that is the host) is a non-default port for ssh. I am trying to change the port forwarding settings (ie guest 22, host 4444) but, when acutally doing `vagrant up`, among the "up" messages, it still reads
```
[default] -- 22 => 2222 (adapter 1)
```
Despite the error message (previous post), the machice is running and I can play with Taiga via `localhost:8000`. I can even do `vagrant ssh` -- of course, this is how I got in, in first place, and ran the installation scripts.

**Comment by superalex** [comment]
Hello @NikosAlexandris,

It's strange, I've just tried taiga-vagrant one more time, I did a git pull to make sure I'm synchronized to the last version and then:

```
vagrant destroy
vagrant up
```

I finish having a working instance of Taiga and if I check the output taiga-scripts is correctly executed. Could you try from another machine to isolate the problem?

**Comment by NikosAlexandris** [comment]
OK, it means I have something strange in my box. In fact, there was some problem with a co-existing older version of net-ssh. I removed it and I am retrying. Thanks for the support.

**Comment by superalex** [comment]
You are welcome!, I'm leaving the issue open until you can confirm that taiga-vagrant works

**Comment by NikosAlexandris** [comment]
I am closing this issue since it has to do with my own system's VirtualBox setup. I have tried it from another machine and it works.  Need to understand what is wrong with my VB installation.

**Comment by superalex** [comment]
Ok! :+1:

**Comment by NikosAlexandris** [comment]
I still did not resolve this problem. So, here an issue for vagrant: https://github.com/mitchellh/vagrant/issues/6686.

**Comment by NikosAlexandris** [comment]
Upgraded vagrant to latest version (1.7.something) and it, finally, works! So happy!

**Comment by superalex** [comment]
Great! :+1:
