### ISSUE TITLE
unable to configure email settings using taiga-vagarant.

### ISSUE THREAD

**Issue by RajaSajja** [taigaio/taiga-vagrant#22]
let me thank you for this vagrant script.how we can configure below mail settings.if i configured in Vagrantfile 
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    ........end
i am not getting mails.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'yourusername@gmail.com'
EMAIL_HOST_PASSWORD = 'yourpassword'

please reply for this .

**Comment by NikosAlexandris** [comment]
After `vagrant up`, connect to your "taiga" virtual machine via ssh. This can be done via `vagrant ssh`. First thing to check are the mail logs (and the others as well in case of errors).  So, what do you read in `/var/log/mail.log`?  You'd need to be root to read the mail log.

**Comment by RajaSajja** [comment]
Thanks for giving reply.
i don't have mail.log in that file.
How to go taiga-back in "taiga" virtual machine via ssh.

**Comment by NikosAlexandris** [comment]
Myself, I still have some configuration issues. So, don't perceive the following as the one and correct way!
 
1. `vagrant up`
2. `vagrant ssh`
3. cd `/home/vagrant/taiga-back/settings`
4. edit the file `local.py` and modify the `EMAIL`-related settings
5. after editing, restart taiga via `circusctl restart taiga`
6. try something like changing a password or adding a new users

Check also details in https://taigaio.github.io/taiga-doc/dist/setup-production.html#_setup_python_environment

**Comment by superalex** [comment]
Thank you very much @NikosAlexandris, I can confirm your instructions about how to configure email in a taiga-vagrant instance are ok! ;)

**Comment by RajaSajja** [comment]
Hi, i followed as you said, but after restart  taiga . i am unable to login in to taiga. its shows oops luma error . username and password is wrong
After this i changed in conf.json  file in taiga-front/dist/js  "api" : "http://localhost:8888/api/v1/"
but its not login into taiga. how can i sortout this issue.

**Comment by NikosAlexandris** [comment]
@RajaSajja see https://groups.google.com/forum/#!topic/taigaio/gyeA7oP1AMI -- perhaps useful!?

**Comment by RajaSajja** [comment]
HI,

i modified  EMAIL_USE_TLS = True  in below configurations , 

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = TRUE 
EMAIL_HOST = "smtp.gmail.com" 
EMAIL_HOST_USER ="username@username.com" 
EMAIL_HOST_PASSWORD = "yourpassword!" 
EMAIL_PORT = 587
 
this time its allowing to login.i crated project,sprint,userstory, task. but i am trying to create new member ,its giving opps luma error, sorry your changes are not saved in database.
  any idea regarding this issue. help me for this.

**Comment by superalex** [comment]
It sounds like your vagrant machine can't connect to the smtp gmail server properly, did you check if you can reach internet from your vagrant instance?

**Comment by superalex** [comment]
Any news about this @RajaSajja ?
