### ISSUE TITLE
Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: Could not read document: Stream closed; nested exception is java.io.IOException: Stream closed

### ISSUE THREAD

**Issue by RajaSajja** [taigaio/taiga-vagrant#23]
when i am trying to post json response to server using post method i got is exception and showing 400 bad request  in advanced rest client tool.

i paased this payload after checking in the json viewer.

{"fullName":"raja","preferredDate":null,"preferredTime":"09:51:PM","taskEndDate":null,"pricingVariantType":"day","bookingAddress":{"locality":"kdr","landmark":"kdr","street":"kdr"},"paymentDetailses":[{"paymentTypes":"card"}]}
this is my method.

@RequestMapping(value="/api/user/driverzzhome",method = RequestMethod.POST, consumes = "application/json")
	public final BookingDetails getUserBookingPage(final HttpServletRequest request, final HttpServletResponse response, @RequestBody final BookingDetails  bookingDetails, @RequestBody final BookingAddress bookingAddress, @RequestBody final PaymentDetails paymentDetails) throws IOException {

--------------

}

why i am getting this. help me.

thanks

**Comment by superalex** [comment]
I'm sorry @RajaSajja but I have no idea what you are talking about...your request seems about something related to payments/bookings and this is a project for the vagrant installation method of the Taiga project (agile management system).
