### ISSUE TITLE
vagrant box defines more cpus than available on host!

### ISSUE THREAD

**Issue by rcabellon** [taigaio/taiga-vagrant#28]
after vagrant up executed the vagranfile creates the virtual machine with 4 cpus, but I only have 2 available.
Then linux never boots up. It hangs, looping the following message:
sd 2:0:0:0 rejecting I/O to offline device

I fixed this by forcing through the VagrantFile to use 2 cpus.

then i found this looking for information about the problem...
it seems tha nproc counts for physical and virtual cores.. and vbox only counts for physical..
https://github.com/hashbangcode/vlad/issues/350

**Comment by superalex** [comment]
Thanks @rcabellon I hope this PR (https://github.com/taigaio/taiga-vagrant/pull/29) can be merged soon.

Regards,
