### ISSUE TITLE
wrong credentials for ubuntu box

### ISSUE THREAD

**Issue by lgzajac** [taigaio/taiga-vagrant#30]
vagrant won't install correctly, because xenial box is wrongly configured
https://bugs.launchpad.net/cloud-images/+bug/1569237

----
EDIT:
I started to test workaround w/bento-ubuntu box
`config.vm.box = "bento/ubuntu-16.04"`, 
`#config.vm.box_url = "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box"`, 
solved a few issues 
1. ssh timeout -> w/ network settings cable  true, 
2. grub2 error w/ apt get update and dpkg fixing, 

but at one moment my system crashed, and i had enough fun, so i will probably setup taiga manually

**Comment by superalex** [comment]
Hello @lgzajac 

I've tried to reproduce the issue but I can't. I've just cloned the repo and after a "vagrant up" everything workind like a charma. 

Could it a be a problem related to your system/network?

**Comment by lgzajac** [comment]
@superalex - thx for the fast reply :)
Although I already had setup taiga manually, I rerun the script just for test, and it works flawlessly today...
It looks like it was some temporary glitch on my Mac OS El Captain  - sorry for troubling you ;)
closing issue.

**Comment by superalex** [comment]
You are welcome @lgzajac thanks for reporting! ;)
